---

- name: Fetch the secret used to connect to the Opnsense device
  set_fact:
    device_secret: "{{ lookup('community.kubernetes.k8s', kind='secret', namespace=api_secret_namespace, resource_name=api_secret_name) }}"

- name: Configure the firewall filter
  dylanturn.opnsense.firewall_filter:
    api_key: "{{ device_secret.data.api_key | b64decode }}"
    api_secret: "{{ device_secret.data.api_secret | b64decode }}"
    api_scheme: "{{ device_secret.data.api_scheme | b64decode }}"
    api_host: "{{ device_secret.data.api_host | b64decode }}"
    api_port: "{{ device_secret.data.api_port | b64decode | int }}"
    api_ca_content: "{{ device_secret.data.api_ca_content | b64decode }}"
    description: "{{ ansible_operator_meta.name | replace('-','_') }}"
    action: "{{ action | default(omit) }}"
    direction: "{{ direction | default(omit) }}"
    interface: "{{ interface | default(omit) }}"
    protocol: "{{ protocol | default(omit) }}"
    source_net: "{{ source_net | default(omit) }}"
    source_port: "{{ source_port | default(omit) }}"
    destination_net: "{{ destination_net | default(omit) }}"
    destination_port: "{{ destination_port | default(omit) }}"
    enabled: "{{ enabled | default(omit) }}"
    state: "{{ state | default(omit) }}"