# permissions for end users to edit firewallfilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallfilter-editor-role
rules:
- apiGroups:
  - opnsense.turnbros.app
  resources:
  - firewallfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opnsense.turnbros.app
  resources:
  - firewallfilters/status
  verbs:
  - get
