# permissions for end users to view firewallalias.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallalias-viewer-role
rules:
- apiGroups:
  - opnsense.turnbros.app
  resources:
  - firewallalias
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opnsense.turnbros.app
  resources:
  - firewallalias/status
  verbs:
  - get
