# permissions for end users to edit firewallalias.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallalias-editor-role
rules:
- apiGroups:
  - opnsense.turnbros.app
  resources:
  - firewallalias
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opnsense.turnbros.app
  resources:
  - firewallalias/status
  verbs:
  - get
