---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for opnsense.turnbros.app/v1alpha1, Kind: FirewallAlias
  ##
  - apiGroups:
      - opnsense.turnbros.app
    resources:
      - firewallalias
      - firewallalias/status
      - firewallalias/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for opnsense.turnbros.app/v1alpha1, Kind: FirewallFilter
  ##
  - apiGroups:
      - opnsense.turnbros.app
    resources:
      - firewallfilters
      - firewallfilters/status
      - firewallfilters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for opnsense.turnbros.app/v1alpha1, Kind: ClusterNodeAlias
  ##
  - apiGroups:
      - opnsense.turnbros.app
    resources:
      - clusternodealias
      - clusternodealias/status
      - clusternodealias/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
