apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: opnsense-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: A Kubernetes operator for managing Opnsense firewalls
  displayName: Opnsense Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - turnbros
  - opnsense
  links:
  - name: Opnsense Operator
    url: https://opnsense-operator.domain
  maturity: alpha
  provider:
    name: turnbros
    url: turnbros.app
  version: 0.0.0
