---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: firewallalias.opnsense.turnbros.app
spec:
  group: opnsense.turnbros.app
  names:
    kind: FirewallAlias
    listKind: FirewallAliasList
    plural: firewallalias
    singular: firewallalias
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FirewallAlias is the Schema for the firewallalias API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of FirewallAlias
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              description:
                type: string
                description: Description of the alias
              type:
                type: string
                description: Type of the alias
              enabled:
                type: boolean
                description: State of the alias
              content:
                type: array
                  items:
                    type: string
                description: The content of this alias (IP, Cidr, url, ...)
              state:
                type: string
                description: Should this alias be present or absent
          status:
            description: Status defines the observed state of FirewallAlias
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}